### ISSUE TITLE
Der Benutzer xxx konnte nicht registriert werden. undefined

### ISSUE THREAD

**Issue by jhartlep** [jamct/webauthn-start#2]
Hi,
ich wollte gerade mal Eure Webauthn-Demo ausprobieren.
Der Start der Docker-Container klappt, ich kann das Frontend aufrufen.
Wenn ich aber versuche, einen User zu registrieren, bekomme ich einen 502 (jquery.js:2 POST http://localhost/auth/register/begin/ 502 (Bad Gateway))

Getestet habe ich das ganze unter Linux Mint 19.1 mit Chrome und einem Yubikey.

Wo liegt denn möglicherweise der Fehler?

Gruß,
Jens

**Comment by jamct** [comment]
Der Fehler ist entstanden, weil der Backend-Container keine Datenbank erzeugen konnte.
Wir haben das Problem gefunden: Docker-Versionen unterscheiden sich darin, wie sie mit der Aufgabe umgehen, eine Datei zu erzeugen, die als Volume in den Container übergeben werden soll. Deswegen lief es nicht auf jeder Maschine...
Die Docker-Compose-Datei ist jetzt geändert, sodass es überall klappt. Sie müssten einmal den Ordner löschen, neu herunterladen, in den Ordner navigieren, die Container neu bauen (`docker-compose build`) und dann starten (`docker-compose up`).
